name: Check Betty Coding Style

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v2

      # Installer Betty
      - name: Install Betty
        run: |
          git clone https://github.com/holbertonschool/Betty.git
          cd Betty
          sudo ./install.sh

      # Exécuter la vérification Betty sur les fichiers *.c
      - name: Run Betty
        run: betty/bin/betty ./**/*.c
